"""add_message_media_and_receipts

Revision ID: ecdb11b297f0
Revises: e06de5852c48
Create Date: 2026-07-13 23:38:03.730465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdb11b297f0'
down_revision: Union[str, Sequence[str], None] = 'e06de5852c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_receipts',
    sa.Column('message_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.add_column('messages', sa.Column('message_type', sa.String(length=50), server_default='text', nullable=False))
    op.add_column('messages', sa.Column('file_url', sa.String(length=1024), nullable=True))
    op.add_column('messages', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('sticker_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sticker_id')
    op.drop_column('messages', 'duration')
    op.drop_column('messages', 'file_url')
    op.drop_column('messages', 'message_type')
    op.drop_table('message_receipts')
    # ### end Alembic commands ###
